// <auto-generated />
using System;
using GpxApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GpxApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331114545_AddIsFirstSyncComplete")]
    partial class AddIsFirstSyncComplete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GpxApi.Models.ActivityRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ActivityJsonIV")
                        .HasColumnType("varbinary(max)");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<byte[]>("EncryptedActivityJson")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("EncryptedGpxData")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("GpxIV")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("MovingTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("StravaActivityId")
                        .HasColumnType("bigint");

                    b.Property<double>("TotalElevationGain")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StravaActivityId")
                        .IsUnique();

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("GpxApi.Models.ActivityStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityRecordId")
                        .HasColumnType("int");

                    b.Property<byte[]>("EncryptedData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("IV")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityRecordId")
                        .IsUnique();

                    b.ToTable("ActivityStreams");
                });

            modelBuilder.Entity("GpxApi.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedAccessToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFirstSyncComplete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("StravaAthleteId")
                        .HasColumnType("bigint");

                    b.Property<string>("StravaName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("TokenExpiresAt")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StravaAthleteId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GpxApi.Models.IntervalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityRecordId")
                        .HasColumnType("int");

                    b.Property<string>("IntervalsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityRecordId");

                    b.ToTable("Intervals");
                });

            modelBuilder.Entity("GpxApi.Models.ActivityRecord", b =>
                {
                    b.HasOne("GpxApi.Models.AppUser", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GpxApi.Models.ActivityStream", b =>
                {
                    b.HasOne("GpxApi.Models.ActivityRecord", "Activity")
                        .WithOne("Stream")
                        .HasForeignKey("GpxApi.Models.ActivityStream", "ActivityRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("GpxApi.Models.IntervalRecord", b =>
                {
                    b.HasOne("GpxApi.Models.ActivityRecord", "Activity")
                        .WithMany("Intervals")
                        .HasForeignKey("ActivityRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("GpxApi.Models.ActivityRecord", b =>
                {
                    b.Navigation("Intervals");

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("GpxApi.Models.AppUser", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
